const sb=supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);let allOrders=[];
const $=id=>document.getElementById(id);
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='Logging in...';const {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){$('loginMsg').textContent=error.message;return}showApp();loadOrders()});
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()};$('refresh').onclick=loadOrders;$('search').oninput=render;$('statusFilter').onchange=render;
async function init(){const {data}=await sb.auth.getSession();if(data.session){showApp();loadOrders()}}function showApp(){$('loginBox').classList.add('hidden');$('app').classList.remove('hidden')}
async function loadOrders(){const {data,error}=await sb.from('orders').select('*').order('created_at',{ascending:false});if(error){$('orders').innerHTML='<div class="order">Orders load হয়নি: '+error.message+'</div>';return}allOrders=data||[];render();stats()}
function stats(){const c=s=>allOrders.filter(o=>(o.status||'New')===s).length;$('newCount').textContent=c('New');$('pickupCount').textContent=c('Pickup');$('ironingCount').textContent=c('Ironing');$('deliveredCount').textContent=c('Delivered')}
function render(){const q=$('search').value.toLowerCase(),s=$('statusFilter').value;const list=allOrders.filter(o=>{const text=[o.name,o.phone,o.address].join(' ').toLowerCase();return(!q||text.includes(q))&&(!s||(o.status||'New')===s)});$('orders').innerHTML=list.length?list.map(orderCard).join(''):'<div class="order">কোনো অর্ডার পাওয়া যায়নি।</div>'}
function orderCard(o){let clothes=[];try{clothes=JSON.parse(o.cloth_type||'[]')}catch{}const items=clothes.map(x=>`${x.name} × ${x.quantity} (৳${x.price})`).join(' · ');const total=clothes.reduce((a,x)=>a+x.quantity*x.price,0);const date=new Date(o.created_at).toLocaleString('bn-BD');return `<article class="order"><div class="order-head"><div><h3>#${o.id} — ${esc(o.name||'Customer')}</h3><div class="muted">${date} · ${esc(o.phone||'')}</div></div><span class="badge">${esc(o.status||'New')}</span></div><div class="details"><div><b>ঠিকানা</b><br>${esc(o.address||'')}</div><div><b>Quantity</b><br>${esc(o.quantity||'0')} টি</div><div><b>Estimated Total</b><br><b>৳${total}</b></div></div><div class="cloth"><b>কাপড়:</b> ${esc(items||'—')}</div><div class="actions"><a href="tel:${esc(o.phone||'')}">📞 Call</a><a href="https://wa.me/88${String(o.phone||'').replace(/^0/,'')}" target="_blank">WhatsApp</a><select onchange="updateStatus(${o.id},this.value)"><option ${o.status==='New'?'selected':''}>New</option><option ${o.status==='Pickup'?'selected':''}>Pickup</option><option ${o.status==='Ironing'?'selected':''}>Ironing</option><option ${o.status==='Ready'?'selected':''}>Ready</option><option ${o.status==='Delivered'?'selected':''}>Delivered</option><option ${o.status==='Cancelled'?'selected':''}>Cancelled</option></select></div></article>`}
async function updateStatus(id,status){const {error}=await sb.from('orders').update({status}).eq('id',id);if(error)alert(error.message);else loadOrders()}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}init();
