create table if not exists public.orders (
 id bigint generated by default as identity primary key,
 created_at timestamptz default now() not null,
 name text,
 phone text,
 address text,
 cloth_type text,
 quantity text,
 status text default 'New'
);
alter table public.orders enable row level security;
drop policy if exists "Anyone can create orders" on public.orders;
create policy "Anyone can create orders" on public.orders for insert to anon with check (true);
-- Replace ADMIN_EMAIL below with your exact Supabase Auth admin email.
drop policy if exists "Admins can read orders" on public.orders;
create policy "Admins can read orders" on public.orders for select to authenticated using (auth.jwt()->>'email' = 'ADMIN_EMAIL');
drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders" on public.orders for update to authenticated using (auth.jwt()->>'email' = 'ADMIN_EMAIL') with check (auth.jwt()->>'email' = 'ADMIN_EMAIL');
